### ISSUE TITLE
How to run the testing web portal you have shown

### ISSUE THREAD

**Issue by willswordh** [Pells31/Vehicle-Make-and-Model-Recognition#1]
Hi, how do you open that web page that is shown? Thanks

**Comment by Pells31** [comment]
Hi there, here you go.

[Vehicle Make and Model Web App](https://pells31-vehicle-make-and-model-recognitio-streamlit-vmmr-l68nwk.streamlit.app/)

**Comment by willswordh** [comment]
@Pells31 Hi, thanks for your quick response! It seems the model can't detect car like Tesla model3 because the datasets are a bit too old. If I want to improve the model, can I add the new annotated datasets into the data folder for training? Thanks

**Comment by Pells31** [comment]
@willswordh That would be great!

Looks like GitHub recommends that ideally repo stays below 1gb and strongly recommends less than 5gb.

I don't remember the total size of the datasets, but I guess if the existing data and new data can fit within the 5gb limit we can store it in the repo.

I agree with you that the app would likely benefit from more training data, both existing examples and new examples.

There are also some small modifications that would need to be made as well to train on the new data (i.e. modifying the train.py script to bring in the new dataset into combined dataframe, etc.)
